[package]
name        = "error_vs"
description = "error_vs"
authors     = [ "decatur.de" ]
edition = "2021"
publish     = false

[dependencies]

# crates.io dependencies
anyhow             = { version = "1.0", features = [ "backtrace" ] }
thiserror          = { version = "1.0" }
snafu = "0.8.5"
tracing            = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [ "ansi", "env-filter", "fmt", "json", "registry", "smallvec" ], default-features = false }

# async-trait      = { workspace = true }
# bson             = { workspace = true }
# futures          = { workspace = true }
# itertools        = { workspace = true }
# serde            = { workspace = true }
# serde_json       = { workspace = true }
# 
# thiserror        = { workspace = true }
# time             = { workspace = true }
# time-tz          = { workspace = true }
# tokio            = { workspace = true }
# tracing          = { workspace = true }
# tracing-subscriber = { workspace = true }
# 
[lib]
doctest = false
